using System.Collections.Generic;

namespace StockAnalyzer.Core.Models.Watchlist
{
    public static class WatchlistColumnRegistry
    {
        public static IReadOnlyList<WatchlistColumnMetadata> AllColumns { get; } = new List<WatchlistColumnMetadata>
        {
            new WatchlistColumnMetadata("Col_Select", "IsChecked", WatchlistConstants.WidthSelect, 1),
            new WatchlistColumnMetadata("Col_Symbol", "Symbol", WatchlistConstants.WidthSymbol, 2),
            new WatchlistColumnMetadata("Col_Name", "Name", WatchlistConstants.WidthName, 3),
            new WatchlistColumnMetadata("Col_Sector", "Sector", WatchlistConstants.WidthSector, 4),
            new WatchlistColumnMetadata("Col_Industry", "Industry", WatchlistConstants.WidthIndustry, 5),
            new WatchlistColumnMetadata("Col_Open", "Open", WatchlistConstants.WidthPrice, 6),
            new WatchlistColumnMetadata("Col_High", "High", WatchlistConstants.WidthPrice, 7),
            new WatchlistColumnMetadata("Col_Low", "Low", WatchlistConstants.WidthPrice, 8),
            new WatchlistColumnMetadata("Col_Price", "Close", WatchlistConstants.WidthPrice, 9),
            new WatchlistColumnMetadata("Col_Volume", "Volume", WatchlistConstants.WidthVolume, 10),
            new WatchlistColumnMetadata("Col_Change", "Change", WatchlistConstants.WidthChange, 11),
            new WatchlistColumnMetadata("Col_Ratio", "ChangePercent", WatchlistConstants.WidthRatio, 12),
            new WatchlistColumnMetadata("Col_ReturnOnEquity", "ReturnOnEquity", "80", 13),
            new WatchlistColumnMetadata("Col_ReturnOnAssets", "ReturnOnAssets", "80", 14),
            new WatchlistColumnMetadata("Col_GrossMargins", "GrossMargins", "80", 15),
            new WatchlistColumnMetadata("Col_OperatingMargins", "OperatingMargins", "80", 16),
            new WatchlistColumnMetadata("Col_ProfitMargins", "ProfitMargins", "80", 17),
            new WatchlistColumnMetadata("Col_CurrentRatio", "CurrentRatio", "80", 18),
            new WatchlistColumnMetadata("Col_DebtToEquity", "DebtToEquity", "80", 19),
            new WatchlistColumnMetadata("Col_Ebitda", "Ebitda", "100", 20),
            new WatchlistColumnMetadata("Col_FreeCashflow", "FreeCashflow", "100", 21),
            new WatchlistColumnMetadata("Col_OperatingCashflow", "OperatingCashflow", "100", 22),
            new WatchlistColumnMetadata("Col_TrailingPE", "TrailingPE", "80", 23),
            new WatchlistColumnMetadata("Col_ForwardPE", "ForwardPE", "80", 24),
            new WatchlistColumnMetadata("Col_PriceToBook", "PriceToBook", "80", 25),
            new WatchlistColumnMetadata("Col_TrailingEps", "TrailingEps", "80", 26),
            new WatchlistColumnMetadata("Col_ForwardEps", "ForwardEps", "80", 27),
            new WatchlistColumnMetadata("Col_BookValue", "BookValue", "80", 28),
            new WatchlistColumnMetadata("Col_SharesOutstanding", "SharesOutstanding", "100", 29),
            new WatchlistColumnMetadata("Col_FloatShares", "FloatShares", "100", 30),
            new WatchlistColumnMetadata("Col_ShortRatio", "ShortRatio", "80", 31),
            new WatchlistColumnMetadata("Col_ShortPercentOfFloat", "ShortPercentOfFloat", "80", 32),
            new WatchlistColumnMetadata("Col_HeldPercentInsiders", "HeldPercentInsiders", "80", 33),
            new WatchlistColumnMetadata("Col_HeldPercentInstitutions", "HeldPercentInstitutions", "80", 34),
            new WatchlistColumnMetadata("Col_LongBusinessSummary", "LongBusinessSummary", "200", 35),
            new WatchlistColumnMetadata("Col_FullTimeEmployees", "FullTimeEmployees", "80", 36),
            new WatchlistColumnMetadata("Col_FiftyTwoWeekHigh", "FiftyTwoWeekHigh", "80", 37),
            new WatchlistColumnMetadata("Col_FiftyTwoWeekLow", "FiftyTwoWeekLow", "80", 38),
            new WatchlistColumnMetadata("Col_RevenueGrowth", "RevenueGrowth", "80", 39),
            new WatchlistColumnMetadata("Col_EarningsGrowth", "EarningsGrowth", "80", 40),
            new WatchlistColumnMetadata("Col_EnterpriseValue", "EnterpriseValue", "100", 41),
            new WatchlistColumnMetadata("Col_EnterpriseToEbitda", "EnterpriseToEbitda", "80", 42),
            new WatchlistColumnMetadata("Col_Beta", "Beta", "80", 43),
            new WatchlistColumnMetadata("Col_PayoutRatio", "PayoutRatio", "80", 44),
            new WatchlistColumnMetadata("Col_DividendRate", "DividendRate", "80", 45),
            new WatchlistColumnMetadata("Col_DividendYield", "DividendYield", "80", 46),
            new WatchlistColumnMetadata("Col_TotalDebt", "TotalDebt", "100", 47),
            new WatchlistColumnMetadata("Col_TotalCash", "TotalCash", "100", 48),
            new WatchlistColumnMetadata("Col_TotalRevenue", "TotalRevenue", "100", 49),
            new WatchlistColumnMetadata("Col_MarketCap", "MarketCap", "100", 50),
            new WatchlistColumnMetadata("Col_PbrCalculated", "PbrCalculated", "80", 51),
            new WatchlistColumnMetadata("Col_DividendYieldCalculated", "DividendYieldCalculated", "80", 52),
            new WatchlistColumnMetadata("Col_EarningsYield", "EarningsYield", "80", 53),
            new WatchlistColumnMetadata("Col_FcfYield", "FcfYield", "80", 54),
            new WatchlistColumnMetadata("Col_FcfMargin", "FcfMargin", "80", 55),
            new WatchlistColumnMetadata("Col_NetDebt", "NetDebt", "100", 56),
            new WatchlistColumnMetadata("Col_NetDebtToEbitda", "NetDebtToEbitda", "80", 57),
            new WatchlistColumnMetadata("Col_DividendCoverage", "DividendCoverage", "80", 58),
            new WatchlistColumnMetadata("Col_PctFromFiftyTwoWeekHigh", "PctFromFiftyTwoWeekHigh", "80", 59),
            new WatchlistColumnMetadata("Col_FloatRatio", "FloatRatio", "80", 60),
            new WatchlistColumnMetadata("Col_MarketCapPerEmployee", "MarketCapPerEmployee", "100", 61),
            new WatchlistColumnMetadata("Col_PegRatio", "PegRatio", "80", 62),
            new WatchlistColumnMetadata("Col_OperatingCashFlowYield", "OperatingCashFlowYield", "80", 63),
            new WatchlistColumnMetadata("Col_NetCashRatio", "NetCashRatio", "80", 64),
            new WatchlistColumnMetadata("Col_PriceToSalesTrailing12Months", "PriceToSalesTrailing12Months", "80", 65),
            new WatchlistColumnMetadata("Col_EnterpriseToRevenue", "EnterpriseToRevenue", "80", 66),
            new WatchlistColumnMetadata("Col_EbitdaMargins", "EbitdaMargins", "80", 67),
            new WatchlistColumnMetadata("Col_QuickRatio", "QuickRatio", "80", 68),
            new WatchlistColumnMetadata("Col_AverageVolume", "AverageVolume", "100", 69),
            new WatchlistColumnMetadata("Col_PriceToCashFlowRatio", "PriceToCashFlowRatio", "80", 70),
            new WatchlistColumnMetadata("Col_NetDebtEquityRatio", "NetDebtEquityRatio", "80", 71),
            new WatchlistColumnMetadata("Col_FiftyTwoWeekRangePosition", "FiftyTwoWeekRangePosition", "80", 72),
            new WatchlistColumnMetadata("Col_DailyTurnoverRate", "DailyTurnoverRate", "80", 73),
            new WatchlistColumnMetadata("Col_AverageTurnoverRate", "AverageTurnoverRate", "80", 74),
            new WatchlistColumnMetadata("Col_DailyFloatShareTurnoverRatio", "DailyFloatShareTurnoverRatio", "80", 75),
            new WatchlistColumnMetadata("Col_AverageFloatTurnover", "AverageFloatTurnover", "80", 76),
            new WatchlistColumnMetadata("Col_ExDividendDate", "ExDividendDate", "100", 77),
            new WatchlistColumnMetadata("Col_ExchangeTimezoneName", "ExchangeTimezoneName", "120", 78),
            new WatchlistColumnMetadata("Col_GmtOffSetMilliseconds", "GmtOffSetMilliseconds", "100", 79),
            new WatchlistColumnMetadata("Col_LastFiscalYearEnd", "LastFiscalYearEnd", "100", 80),
            new WatchlistColumnMetadata("Col_MostRecentQuarter", "MostRecentQuarter", "100", 81),
            new WatchlistColumnMetadata("Col_NumberOfAnalystOpinions", "NumberOfAnalystOpinions", "100", 82),
            new WatchlistColumnMetadata("Col_QuoteType", "QuoteType", "100", 83),
            new WatchlistColumnMetadata("Col_RecommendationKey", "RecommendationKey", "100", 84),
            new WatchlistColumnMetadata("Col_RecommendationMean", "RecommendationMean", "100", 85),
            new WatchlistColumnMetadata("Col_Region", "Region", "100", 86),
            new WatchlistColumnMetadata("Col_TargetHighPrice", "TargetHighPrice", "100", 87),
            new WatchlistColumnMetadata("Col_TargetLowPrice", "TargetLowPrice", "100", 88),
            new WatchlistColumnMetadata("Col_TargetMeanPrice", "TargetMeanPrice", "100", 89),
            new WatchlistColumnMetadata("Col_TargetMedianPrice", "TargetMedianPrice", "100", 90),
            new WatchlistColumnMetadata("Col_LastUpdatedUtc", "LastUpdatedUtc", "120", 91),
            new WatchlistColumnMetadata("Col_MetadataLastUpdated", "MetadataLastUpdated", "120", 92),
            new WatchlistColumnMetadata("Col_Tag", "Tag", "100", 93)
        };
    }
}
