using System;
using System.Collections.Generic;
using StockAnalyzer.Core.Models;

namespace StockAnalyzer.Core.Utilities
{
    /// <summary>
    /// Represents the type of a recognized Point and Figure pattern.
    /// </summary>
    public enum PnfPatternType
    {
        // Simple breakouts
        DoubleTopBreakout,
        DoubleBottomBreakout,

        // Internal trendline breakouts (Step 2)
        BullishSupportLineBreakout,
        BearishResistanceLineBreakout,

        // Complex formations (Step 3)
        TripleTopBreakout,
        TripleBottomBreakout,
        BullishCatapult,
        BearishCatapult,
        BullishTriangleBreakout,
        BearishTriangleBreakout
    }

    /// <summary>
    /// Represents a signal emitted by the Point and Figure pattern engine.
    /// </summary>
    public readonly record struct PnfSignal(
        PnfPatternType PatternType,
        bool IsBullish,
        DateTime TriggerTimestamp,
        decimal TriggerPrice,
        decimal SignalLevel, // e.g., the high of the previous X column that was broken
        int AnchorColOffset = 0 // Number of columns back to the start/anchor of the pattern
    );

    /// <summary>
    /// Represents a currently active (unbroken) trendline in a P&F chart.
    /// </summary>
    public readonly record struct PnfTrendline(
        int AnchorIndex, 
        decimal AnchorPrice, 
        bool IsBullish
    );

    /// <summary>
    /// Represents the full analysis result including triggered signals and active trendlines.
    /// </summary>
    public readonly record struct PnfAnalysisResult(
        IReadOnlyList<PnfSignal> Signals,
        IReadOnlyList<PnfTrendline> ActiveLines
    );

    /// <summary>
    /// Engine to detect Point & Figure patterns and breakouts from a sequence of P&F columns.
    /// Uses the output of PointAndFigureConverter (List&lt;CandleData&gt;).
    /// </summary>
    public static class PointAndFigurePatternEngine
    {
        private record struct Trendline(int AnchorIndex, decimal AnchorPrice);

        [ThreadStatic]
        private static List<Trendline>? _activeBullishLinesLocal;
        [ThreadStatic]
        private static List<Trendline>? _activeBearishLinesLocal;

        /// <summary>
        /// Analyzes a sequence of P&F columns and returns detected signals.
        /// </summary>
        /// <param name="columns">The P&F columns (X and O columns as generated by PointAndFigureConverter).</param>
        /// <param name="boxSize">The box size used to generate the columns.</param>
        /// <returns>An analysis result containing signals and active trendlines.</returns>
        public static PnfAnalysisResult Analyze(IReadOnlyList<CoreCandleData> columns, decimal boxSize)
        {
            var signals = new List<PnfSignal>(16);
            var activeLines = new List<PnfTrendline>(16);
            return Analyze(columns, boxSize, signals, activeLines);
        }

        /// <summary>
        /// Analyzes a sequence of P&F columns and populates the provided buffers to avoid heap allocations.
        /// </summary>
        /// <param name="columns">The P&F columns (X and O columns as generated by PointAndFigureConverter).</param>
        /// <param name="boxSize">The box size used to generate the columns.</param>
        /// <param name="signals">Buffer to populate with detected signals.</param>
        /// <param name="activeLines">Buffer to populate with active trendlines.</param>
        /// <returns>An analysis result referencing the provided buffers.</returns>
        public static PnfAnalysisResult Analyze(
            IReadOnlyList<CoreCandleData> columns, 
            decimal boxSize,
            List<PnfSignal> signals,
            List<PnfTrendline> activeLines)
        {
            signals.Clear();
            activeLines.Clear();

            // Need at least 3 columns to form a basic double top/bottom breakout
            if (columns == null || columns.Count < 3)
                return new PnfAnalysisResult(signals, activeLines);

            _activeBullishLinesLocal ??= new List<Trendline>(16);
            _activeBearishLinesLocal ??= new List<Trendline>(16);
            _activeBullishLinesLocal.Clear();
            _activeBearishLinesLocal.Clear();

            var activeBullishLines = _activeBullishLinesLocal;
            var activeBearishLines = _activeBearishLinesLocal;

            for (int i = 2; i < columns.Count; i++)
            {
                var col = columns[i];
                var prev1 = columns[i - 1]; // Previous column (opposite direction)
                var prev2 = columns[i - 2]; // Column before previous (same direction as col)
                
                bool isUp = col.Close >= col.Open;
                bool isPrev2Up = prev2.Close >= prev2.Open;

                if (isUp == isPrev2Up)
                {
                    // Check complex formations first (requires more history)
                    bool isTripleTop = false;
                    bool isTripleBottom = false;

                    if (i >= 4)
                    {
                        var prev4 = columns[i - 4]; // Same direction as current
                        bool isPrev4Up = prev4.Close >= prev4.Open;

                        if (isUp && isPrev4Up) // All 3 columns are X
                        {
                            // Triple Top Breakout
                            // WebAI Fix: Strict equality check for the peaks (prev2 and prev4)
                            if (Math.Abs(prev2.High - prev4.High) < 0.0001m && col.High > prev2.High)
                            {
                                isTripleTop = true;
                                decimal signalLevel = prev2.High;

                                signals.Add(new PnfSignal(
                                    PatternType: PnfPatternType.TripleTopBreakout,
                                    IsBullish: true,
                                    TriggerTimestamp: col.Timestamp,
                                    TriggerPrice: signalLevel + boxSize,
                                    SignalLevel: signalLevel,
                                    AnchorColOffset: 4
                                ));
                            }
                            
                            // Bullish Triangle Breakout (Higher Lows, Lower Highs culminating in a breakout)
                            // A triangle breakout implies converging trendlines. 
                            // For a Bullish Triangle (X breaks out):
                            // Col (i) is X. Prev2 (i-2) is X. Prev4 (i-4) is X.
                            // To be converging: prev2.High < prev4.High (Lower Highs on X)
                            // Prev1 (i-1) is O. Prev3 (i-3) is O. 
                            // To be converging: prev1.Low > prev3.Low (Higher Lows on O)
                            // Breakout: col.High > prev2.High
                            // NOTE: Minimum sequence is Prev4, Prev3, Prev2, Prev1, Col -> 5 columns, so i >= 4.
                            if (i >= 4)
                            {
                                var prev1Triangle = columns[i - 1]; // O col
                                var prev3Triangle = columns[i - 3]; // O col
                                if (prev2.High < prev4.High && prev1Triangle.Low > prev3Triangle.Low && col.High > prev2.High)
                                {
                                    signals.Add(new PnfSignal(
                                        PatternType: PnfPatternType.BullishTriangleBreakout,
                                        IsBullish: true,
                                        TriggerTimestamp: col.Timestamp,
                                        TriggerPrice: prev2.High + boxSize,
                                        SignalLevel: prev2.High,
                                        AnchorColOffset: 4
                                    ));
                                }
                            }
                        }
                        else if (!isUp && !isPrev4Up) // All 3 columns are O
                        {
                            // Triple Bottom Breakout
                            // WebAI Fix: Strict equality check for the troughs (prev2 and prev4)
                            if (Math.Abs(prev2.Low - prev4.Low) < 0.0001m && col.Low < prev2.Low)
                            {
                                isTripleBottom = true;
                                decimal signalLevel = prev2.Low;

                                signals.Add(new PnfSignal(
                                    PatternType: PnfPatternType.TripleBottomBreakout,
                                    IsBullish: false,
                                    TriggerTimestamp: col.Timestamp,
                                    TriggerPrice: signalLevel - boxSize,
                                    SignalLevel: signalLevel,
                                    AnchorColOffset: 4
                                ));
                            }

                            // Bearish Triangle Breakout (Lower Highs, Higher Lows culminating in a breakdown)
                            // For a Bearish Triangle (O breaks down):
                            // Col (i) is O. Prev2 (i-2) is O. Prev4 (i-4) is O.
                            // To be converging: prev2.Low > prev4.Low (Higher Lows on O)
                            // Prev1 (i-1) is X. Prev3 (i-3) is X.
                            // To be converging: prev1.High < prev3.High (Lower Highs on X)
                            // Breakout: col.Low < prev2.Low
                            if (i >= 4)
                            {
                                var prev1Triangle = columns[i - 1]; // X col
                                var prev3Triangle = columns[i - 3]; // X col
                                if (prev2.Low > prev4.Low && prev1Triangle.High < prev3Triangle.High && col.Low < prev2.Low)
                                {
                                    signals.Add(new PnfSignal(
                                        PatternType: PnfPatternType.BearishTriangleBreakout,
                                        IsBullish: false,
                                        TriggerTimestamp: col.Timestamp,
                                        TriggerPrice: prev2.Low - boxSize,
                                        SignalLevel: prev2.Low,
                                        AnchorColOffset: 4
                                    ));
                                }
                            }
                        }
                    }

                    // Basic Double Top / Double Bottom
                    // We only record a Double Top if it wasn't already classified as a Triple Top (to avoid duplicate signals for the same event)
                    if (isUp) // Current is X column
                    {
                        // Filter: Only consider if prev2 is a significant peak or has sufficient height.
                        // A column is at least 3 boxes tall if High - Low >= 2 * boxSize
                        bool isSignificant = (prev2.High - prev2.Low >= 2 * boxSize) || 
                                             (i >= 4 && prev2.High > columns[i - 4].High);

                        if (!isTripleTop && isSignificant && col.High > prev2.High)
                        {
                            decimal signalLevel = prev2.High;

                            // WebAI Fix: Catapult triggers on the 2nd wave (Double Top following a Triple Top)
                            bool isCatapult = false;
                            if (i >= 6)
                            {
                                var prev4Cat = columns[i - 4];
                                var prev6 = columns[i - 6];
                                // Sequence: prev6==prev4 (base), prev2 > prev4 (Triple Breakout), col > prev2 (Catapult/Double Breakout)
                                if (prev2.High > prev4Cat.High && Math.Abs(prev4Cat.High - prev6.High) < 0.0001m)
                                {
                                    isCatapult = true;
                                    signals.Add(new PnfSignal(
                                        PatternType: PnfPatternType.BullishCatapult,
                                        IsBullish: true,
                                        TriggerTimestamp: col.Timestamp,
                                        TriggerPrice: signalLevel + boxSize,
                                        SignalLevel: signalLevel,
                                        AnchorColOffset: 6
                                    ));
                                }
                            }

                            if (!isCatapult)
                            {
                                signals.Add(new PnfSignal(
                                    PatternType: PnfPatternType.DoubleTopBreakout,
                                    IsBullish: true,
                                    TriggerTimestamp: col.Timestamp,
                                    TriggerPrice: signalLevel + boxSize,
                                    SignalLevel: signalLevel,
                                    AnchorColOffset: 2
                                ));
                            }
                        }
                    }
                    else // Current is O column
                    {
                        // Filter: Only consider if prev2 is a significant trough or has sufficient depth.
                        bool isSignificant = (prev2.High - prev2.Low >= 2 * boxSize) || 
                                             (i >= 4 && prev2.Low < columns[i - 4].Low);

                        if (!isTripleBottom && isSignificant && col.Low < prev2.Low)
                        {
                            decimal signalLevel = prev2.Low;

                            // WebAI Fix: Catapult triggers on the 2nd wave (Double Bottom following a Triple Bottom)
                            bool isCatapult = false;
                            if (i >= 6)
                            {
                                var prev4Cat = columns[i - 4];
                                var prev6 = columns[i - 6];
                                // Sequence: prev6==prev4 (base), prev2 < prev4 (Triple Breakout), col < prev2 (Catapult/Double Breakout)
                                if (prev2.Low < prev4Cat.Low && Math.Abs(prev4Cat.Low - prev6.Low) < 0.0001m)
                                {
                                    isCatapult = true;
                                    signals.Add(new PnfSignal(
                                        PatternType: PnfPatternType.BearishCatapult,
                                        IsBullish: false,
                                        TriggerTimestamp: col.Timestamp,
                                        TriggerPrice: signalLevel - boxSize,
                                        SignalLevel: signalLevel,
                                        AnchorColOffset: 6
                                    ));
                                }
                            }

                            if (!isCatapult)
                            {
                                signals.Add(new PnfSignal(
                                    PatternType: PnfPatternType.DoubleBottomBreakout,
                                    IsBullish: false,
                                    TriggerTimestamp: col.Timestamp,
                                    TriggerPrice: signalLevel - boxSize,
                                    SignalLevel: signalLevel,
                                    AnchorColOffset: 2
                                ));
                            }
                        }
                    }
                }
            }

            // Step 2: 45-Degree Internal Trendlines Analysis
            for (int i = 0; i < columns.Count; i++)
            {
                var col = columns[i];
                bool isUp = col.Close >= col.Open;

                if (isUp)
                {
                    // Check for Bearish Resistance Line Breakouts
                    for (int j = activeBearishLines.Count - 1; j >= 0; j--)
                    {
                        var line = activeBearishLines[j];
                        decimal lineValue = line.AnchorPrice - (i - line.AnchorIndex) * boxSize;

                        if (col.High > lineValue) // Broken
                        {
                            // Output signal ONLY if the line survived at least one cycle (i.e. i - anchor >= 4)
                            if (i - line.AnchorIndex >= 4)
                            {
                                signals.Add(new PnfSignal(
                                    PatternType: PnfPatternType.BearishResistanceLineBreakout,
                                    IsBullish: true,
                                    TriggerTimestamp: col.Timestamp,
                                    TriggerPrice: lineValue + boxSize,
                                    SignalLevel: lineValue,
                                    AnchorColOffset: i - line.AnchorIndex
                                ));
                            }
                            activeBearishLines.RemoveAt(j);
                        }
                    }

                    // Treat every X column top as a potential anchor for a Bearish Resistance Line
                    // Filter: Only add anchor if it is a major peak (higher than the previous 2 peaks) to reduce noise
                    bool isSignificantPeak = true;
                    if (i >= 2 && columns[i - 2].High > col.High) isSignificantPeak = false;
                    if (i >= 4 && columns[i - 4].High > col.High) isSignificantPeak = false;
                    
                    if (isSignificantPeak)
                    {
                        activeBearishLines.Add(new Trendline(i, col.High));
                    }
                }
                else
                {
                    // Check for Bullish Support Line Breakouts
                    for (int j = activeBullishLines.Count - 1; j >= 0; j--)
                    {
                        var line = activeBullishLines[j];
                        decimal lineValue = line.AnchorPrice + (i - line.AnchorIndex) * boxSize;

                        if (col.Low < lineValue) // Broken
                        {
                            // Output signal ONLY if the line survived at least one cycle (i.e. i - anchor >= 4)
                            if (i - line.AnchorIndex >= 4)
                            {
                                signals.Add(new PnfSignal(
                                    PatternType: PnfPatternType.BullishSupportLineBreakout,
                                    IsBullish: false,
                                    TriggerTimestamp: col.Timestamp,
                                    TriggerPrice: lineValue - boxSize,
                                    SignalLevel: lineValue,
                                    AnchorColOffset: i - line.AnchorIndex
                                ));
                            }
                            activeBullishLines.RemoveAt(j);
                        }
                    }

                    // Treat every O column bottom as a potential anchor for a Bullish Support Line
                    // Filter: Only add anchor if it is a major trough (lower than the previous 2 troughs) to reduce noise
                    bool isSignificantTrough = true;
                    if (i >= 2 && columns[i - 2].Low < col.Low) isSignificantTrough = false;
                    if (i >= 4 && columns[i - 4].Low < col.Low) isSignificantTrough = false;
                    
                    if (isSignificantTrough)
                    {
                        activeBullishLines.Add(new Trendline(i, col.Low));
                    }
                }
            }

            // Capture the currently active lines (those not broken)
            foreach (var line in activeBullishLines)
            {
                activeLines.Add(new PnfTrendline(line.AnchorIndex, line.AnchorPrice, true));
            }
            foreach (var line in activeBearishLines)
            {
                activeLines.Add(new PnfTrendline(line.AnchorIndex, line.AnchorPrice, false));
            }

            // Sort signals by timestamp primarily to maintain temporal order
            signals.Sort((a, b) => a.TriggerTimestamp.CompareTo(b.TriggerTimestamp));
            
            return new PnfAnalysisResult(signals, activeLines);
        }
    }
}
